//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoCaoLoiTramTiepNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatTrinhXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhatTrinhXe()
        {
            this.Transfer_NhatKyTruyenTaiDuLieu = new HashSet<Transfer_NhatKyTruyenTaiDuLieu>();
        }
    
        public long Id { get; set; }
        public Nullable<long> TX_IdXe { get; set; }
        public Nullable<long> LT_IdLuongTuyen { get; set; }
        public Nullable<int> CT_IdCongTyVT { get; set; }
        public Nullable<int> IdBenDi { get; set; }
        public string BienSoDi { get; set; }
        public Nullable<System.DateTime> GioVaoBen { get; set; }
        public Nullable<System.DateTime> GioXuatBenKeHoach { get; set; }
        public Nullable<System.DateTime> GioCapXuatBen { get; set; }
        public Nullable<System.DateTime> GioRaBen { get; set; }
        public Nullable<int> SoKhach { get; set; }
        public Nullable<bool> XeXepKhach { get; set; }
        public Nullable<bool> XeKhongDuDieuKien { get; set; }
        public Nullable<bool> XeVeDonVi { get; set; }
        public Nullable<bool> XeTangCuong { get; set; }
        public Nullable<int> IdBenDen { get; set; }
        public Nullable<System.DateTime> GioDenBen { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> GioTaoMoi { get; set; }
        public Nullable<System.DateTime> GioCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer_NhatKyTruyenTaiDuLieu> Transfer_NhatKyTruyenTaiDuLieu { get; set; }
    }
}
