//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoCaoLoiTramTiepNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer_NhatKyTruyenTaiDuLieu
    {
        public long IDNhatKyTruyenTaiDuLieu { get; set; }
        public long IDApplicationSession { get; set; }
        public string Loai { get; set; }
        public string DuLieu { get; set; }
        public long MaLoi { get; set; }
        public string Loi { get; set; }
        public string ChanDoan { get; set; }
        public string RawError { get; set; }
        public string RawRequest { get; set; }
        public string ThongTinThem { get; set; }
        public Nullable<long> IDNhatTrinhXe { get; set; }
        public System.DateTime NgayGhi { get; set; }
    
        public virtual NhatTrinhXe NhatTrinhXe { get; set; }
    }
}
